swagger: "2.0"
info:
  title: EngineerCMS API
  description: ECMS has every tool to get any job done, so codename for the new ECMS
    APIs.
  version: 1.0.0
  contact:
    email: 504284@qq.com
basePath: /v1
paths:
  /admin/:
    get:
      tags:
      - admin
      description: get admin page
      operationId: AdminController.getAdminBlock
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.success'
        "400":
          description: Invalid page
        "404":
          description: page not found
  /admin/category/{id}:
    get:
      tags:
      - admin
      description: Get Category list by some info
      operationId: AdminController.Get Category list
      parameters:
      - in: path
        name: id
        description: category id
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.GetAdminCategory'
  /admin/category/addcategory:
    post:
      tags:
      - admin
      description: Get Category list by title info
      operationId: AdminController.Post Category by pid title code grade
      parameters:
      - in: query
        name: pid
        description: parentid of category
        type: string
      - in: query
        name: title
        description: title of category
        type: string
      - in: query
        name: code
        description: code of category
        type: string
      - in: query
        name: grade
        description: grade of category
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.AddAdminCategory'
  /admin/categorytitle:
    get:
      tags:
      - admin
      description: Get Category list by title info
      operationId: AdminController.Get Category by title
      parameters:
      - in: query
        name: title
        description: title of search
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.GetAdminCategory'
  /adminlog/errlog:
    get:
      tags:
      - adminlog
      description: get log list
      operationId: AdminLogController.getAdminBlock
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.success'
        "400":
          description: Invalid page
        "404":
          description: page not found
  /adminlog/infolog:
    get:
      tags:
      - adminlog
      description: get log list
      operationId: AdminLogController.getAdminBlock
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.success'
        "400":
          description: Invalid page
        "404":
          description: page not found
  /wx/addwxarticle:
    post:
      tags:
      - wx
      description: post article by catalogid
      operationId: ArticleController.post wx artile by catalogId
      parameters:
      - in: query
        name: title
        description: The title of article
        required: true
        type: string
      - in: query
        name: content
        description: The content of article
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.AddArticle'
        "400":
          description: Invalid page supplied
        "404":
          description: articl not found
  /wx/getwxarticle/{id}:
    get:
      tags:
      - wx
      description: get article by articleid
      operationId: ArticleController.get wx artile by articleId
      parameters:
      - in: path
        name: id
        description: The id of article
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.GetArticle'
        "400":
          description: Invalid page supplied
        "404":
          description: articl not found
  /wx/getwxarticles:
    get:
      tags:
      - wx
      description: get articles by page
      operationId: ArticleController.get wx artiles list
      parameters:
      - in: query
        name: page
        description: The page for articles list
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.GetProductsPage'
        "400":
          description: Invalid page supplied
        "404":
          description: articls not found
  /wx/uploadwximg:
    post:
      tags:
      - wx
      description: post article img by catalogid
      operationId: FroalaController.post wx artile img by catalogId
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.SUCCESS'
        "400":
          description: Invalid page supplied
        "404":
          description: articl not found
  /wx/wxlogin:
    get:
      tags:
      - wx
      description: post wx login
      operationId: LoginController.post wx login
      parameters:
      - in: path
        name: code
        description: The jscode of wxuser
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.success'
        "400":
          description: Invalid page supplied
        "404":
          description: articl not found
definitions:
  .AddAdminCategory:
    type: object
  .AddArticle:
    type: object
  .GetAdminCategory:
    type: object
  .GetArticle:
    type: object
  .GetProductsPage:
    type: object
  .SUCCESS:
    type: object
  .success:
    type: object
tags:
- name: admin
  description: |
    CMSADMIN API
- name: wx
  description: |
    CMSWX login API
- name: adminlog
  description: |
    CMSADMIN API
